# Generated by Django 4.2.5 on 2023-10-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211130_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
