# Generated by Django 4.2.5 on 2023-10-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
